-- Insert sample system settings for testing
INSERT INTO system_settings (setting_key, setting_value, created_at, updated_at) VALUES
('app.name', 'MMO Market System', NOW(), NOW()),
('app.version', '1.0.0', NOW(), NOW()),
('app.description', 'A marketplace for digital goods and services', NOW(), NOW()),
('payment.fee.percentage', '5.0', NOW(), NOW()),
('payment.fee.minimum', '1000', NOW(), NOW()),
('payment.fee.maximum', '100000', NOW(), NOW()),
('email.smtp.host', 'smtp.gmail.com', NOW(), NOW()),
('email.smtp.port', '587', NOW(), NOW()),
('email.smtp.username', 'noreply@mmomarket.com', NOW(), NOW()),
('email.smtp.password', 'encrypted_password_here', NOW(), NOW()),
('security.jwt.secret', 'your-secret-key-here', NOW(), NOW()),
('security.jwt.expiration', '86400', NOW(), NOW()),
('security.password.min_length', '8', NOW(), NOW()),
('security.password.require_special', 'true', NOW(), NOW()),
('storage.max_file_size', '10485760', NOW(), NOW()),
('storage.allowed_extensions', 'jpg,jpeg,png,gif,pdf,doc,docx', NOW(), NOW()),
('notification.email.enabled', 'true', NOW(), NOW()),
('notification.sms.enabled', 'false', NOW(), NOW()),
('notification.push.enabled', 'true', NOW(), NOW()),
('maintenance.mode', 'false', NOW(), NOW()),
('maintenance.message', 'System is under maintenance. Please try again later.', NOW(), NOW()),
('features.registration.enabled', 'true', NOW(), NOW()),
('features.verification.required', 'true', NOW(), NOW()),
('features.review.enabled', 'true', NOW(), NOW()),
('features.chat.enabled', 'true', NOW(), NOW());
